
<section>
    <div class="container-fluid mt-5">
        <div class="row">
            <div class="col-lg-6" style="border-right: 2px solid orange;padding: 40px;">
                <h3 class="mb-3">Autenticar:</h3>
                <form method="post" action="/autenticarDb">
                    <label>Seu Email:</label>
                    <input class="form-control" type="text" name="email">
                    <label>Sua Senha:</label>
                    <input class="form-control" type="text" name="senha">
                 
                    <button style="width: 100%;background-color: orange;color: white;margin-top: 19px;border: 2px solid black;" type="submit">Entrar</button>
                 </form>
            </div>

            <div class="col-lg-6" style="padding: 40px;">
                <h3  class="mb-3">Registrar:</h3>
                <form method="post" action="/registroDb">
                    <label>Seu Nome:</label>
                    <input class="form-control" type="text" name="nome">
                    <label>Seu Email:</label>
                    <input class="form-control" type="text" name="email">
                    <label>Sua Senha:</label>
                    <input class="form-control" type="text" name="senha">
                 
                    <button style="width: 100%;background-color: orange;color: white;margin-top: 19px;border: 2px solid black;" type="submit">Registrar</button>
                </form>
            </div>
        </div>
    </div>
</section>